import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790198866649 implements MigrationInterface {
    name = 'InitialSchema1790198866649'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."otp_codes_purpose_enum" AS ENUM('LOGIN', 'VERIFY_PHONE')`);
        await queryRunner.query(`CREATE TABLE "otp_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying(20) NOT NULL, "purpose" "public"."otp_codes_purpose_enum" NOT NULL, "codeHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "consumedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9d0487965ac1837d57fec4d6a26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ca53c9789e16452c4c202ebfb" ON "otp_codes" ("phone", "purpose", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('PENDING_PAYMENT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "touristId" uuid NOT NULL, "guideId" uuid NOT NULL, "packageId" uuid NOT NULL, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'PENDING_PAYMENT', "startAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endAt" TIMESTAMP WITH TIME ZONE NOT NULL, "groupSize" integer NOT NULL, "subtotalMinor" integer NOT NULL, "platformFeeMinor" integer NOT NULL, "guidePayoutMinor" integer NOT NULL, "totalMinor" integer NOT NULL, "currency" character(3) NOT NULL, "notes" text, "paymentDueAt" TIMESTAMP WITH TIME ZONE, "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "cancelledAt" TIMESTAMP WITH TIME ZONE, "cancelledById" uuid, "cancellationReason" text, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78a18a5704f657786240cbe82e" ON "bookings" ("touristId") `);
        await queryRunner.query(`CREATE INDEX "IDX_48b267d894e32a25ebde4b207a" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_17c8a50ad52487f8bb826752df" ON "bookings" ("guideId", "startAt") `);
        await queryRunner.query(`CREATE TABLE "sos_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "raisedById" uuid NOT NULL, "location" geography(Point,4326), "message" text, "acknowledgedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5c6f2f5f40ab2224315e007b9c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1d9158fe8a16cbe60dd55c1494" ON "sos_alerts" ("bookingId") `);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('OPEN', 'RESOLVED')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_resolution_enum" AS ENUM('REFUND_TOURIST', 'RELEASE_TO_GUIDE', 'PARTIAL_REFUND')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "bookingId" uuid NOT NULL, "openedById" uuid NOT NULL, "reason" character varying(64) NOT NULL, "description" text NOT NULL DEFAULT '', "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'OPEN', "resolution" "public"."disputes_resolution_enum", "refundPercent" integer, "resolvedById" uuid, "resolvedAt" TIMESTAMP WITH TIME ZONE, "resolutionNote" text, CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_238a0a4e4dc39f4a8984e633fe" ON "disputes" ("bookingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ea46f4f2225f38d127063c367" ON "disputes" ("status") `);
        await queryRunner.query(`CREATE TABLE "cities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "countryId" uuid NOT NULL, "location" geography(Point,4326) NOT NULL, "timezone" character varying(64) NOT NULL DEFAULT 'UTC', CONSTRAINT "PK_4762ffb6e5d198cfec5606bc11e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b0c5868a3c4663b0e72a6030a6" ON "cities" USING GiST ("location") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_89ecbef65dda32fcf45ae09e2f" ON "cities" ("countryId", "name") `);
        await queryRunner.query(`CREATE TABLE "countries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character(2) NOT NULL, "name" character varying(100) NOT NULL, "currency" character(3) NOT NULL, CONSTRAINT "UQ_b47cbb5311bad9c9ae17b8c1eda" UNIQUE ("code"), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sites_category_enum" AS ENUM('HERITAGE', 'MUSEUM', 'NATURE', 'RELIGIOUS', 'CITY', 'ADVENTURE', 'FOOD')`);
        await queryRunner.query(`CREATE TABLE "sites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(160) NOT NULL, "description" text NOT NULL DEFAULT '', "category" "public"."sites_category_enum" NOT NULL, "cityId" uuid NOT NULL, "location" geography(Point,4326) NOT NULL, "imageUrl" character varying, "requiresLicensedGuide" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_4f5eccb1dfde10c9170502595a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a7dbd4513de54a315d97e1a7d" ON "sites" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_1516efb8cd9a59205e85a1a9a9" ON "sites" USING GiST ("location") `);
        await queryRunner.query(`CREATE TYPE "public"."guides_verificationstatus_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TYPE "public"."guides_kycstatus_enum" AS ENUM('NOT_STARTED', 'CLEAR', 'CONSIDER', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "guides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "bio" text NOT NULL DEFAULT '', "languages" text array NOT NULL DEFAULT '{}', "yearsOfExperience" integer NOT NULL DEFAULT '0', "licenseNumber" character varying(64), "licenseCountryId" uuid, "licenseExpiresAt" date, "licenseDocumentUrl" character varying, "verificationStatus" "public"."guides_verificationstatus_enum" NOT NULL DEFAULT 'DRAFT', "submittedAt" TIMESTAMP WITH TIME ZONE, "verifiedAt" TIMESTAMP WITH TIME ZONE, "verifiedById" uuid, "rejectionReason" text, "kycStatus" "public"."guides_kycstatus_enum" NOT NULL DEFAULT 'NOT_STARTED', "kycReference" character varying, "kycResult" jsonb, "ratingAvg" numeric(3,2) NOT NULL DEFAULT '0', "ratingCount" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_6fb9ae622c0f4c05653408ee58f" UNIQUE ("userId"), CONSTRAINT "REL_6fb9ae622c0f4c05653408ee58" UNIQUE ("userId"), CONSTRAINT "PK_8de34e682c2201d625cf95c1266" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d3e810892714fd8723b017073c" ON "guides" ("licenseNumber") WHERE "licenseNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_78843aacbd41d7f5d6dbc5522f" ON "guides" ("verificationStatus") `);
        await queryRunner.query(`CREATE TYPE "public"."guide_verification_events_fromstatus_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TYPE "public"."guide_verification_events_tostatus_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "guide_verification_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "guideId" uuid NOT NULL, "fromStatus" "public"."guide_verification_events_fromstatus_enum" NOT NULL, "toStatus" "public"."guide_verification_events_tostatus_enum" NOT NULL, "actorId" uuid, "note" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_319d0737dd3855c3bf936999cdd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_29d9e1bad54935fbebd383a0a9" ON "guide_verification_events" ("guideId") `);
        await queryRunner.query(`CREATE TYPE "public"."tour_packages_pricingtype_enum" AS ENUM('PER_PERSON', 'PER_GROUP')`);
        await queryRunner.query(`CREATE TABLE "tour_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "guideId" uuid NOT NULL, "cityId" uuid NOT NULL, "title" character varying(160) NOT NULL, "description" text NOT NULL DEFAULT '', "durationMinutes" integer NOT NULL, "pricingType" "public"."tour_packages_pricingtype_enum" NOT NULL DEFAULT 'PER_GROUP', "priceMinor" integer NOT NULL, "currency" character(3) NOT NULL, "maxGroupSize" integer NOT NULL DEFAULT '8', "languages" text array NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f6f4175550eb6e5cce18e8b892a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ff20f817e9f4498b3d3ecb746" ON "tour_packages" ("guideId") `);
        await queryRunner.query(`CREATE INDEX "IDX_41f97d6bf3b4d424c83d4bb8fd" ON "tour_packages" ("cityId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_escrowstatus_enum" AS ENUM('PENDING', 'HELD', 'RELEASED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "bookingId" uuid NOT NULL, "provider" character varying(32) NOT NULL, "providerRef" character varying, "amountMinor" integer NOT NULL, "currency" character(3) NOT NULL, "escrowStatus" "public"."payments_escrowstatus_enum" NOT NULL DEFAULT 'PENDING', "refundedMinor" integer NOT NULL DEFAULT '0', "releasedMinor" integer NOT NULL DEFAULT '0', "heldAt" TIMESTAMP WITH TIME ZONE, "releaseAfter" TIMESTAMP WITH TIME ZONE, "releasedAt" TIMESTAMP WITH TIME ZONE, "refundedAt" TIMESTAMP WITH TIME ZONE, "failureReason" text, CONSTRAINT "UQ_1ead3dc5d71db0ea822706e389d" UNIQUE ("bookingId"), CONSTRAINT "REL_1ead3dc5d71db0ea822706e389" UNIQUE ("bookingId"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "bookingId" uuid NOT NULL, "guideId" uuid NOT NULL, "authorId" uuid NOT NULL, "rating" smallint NOT NULL, "comment" text NOT NULL DEFAULT '', "isHidden" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_c357057587a1c2afae453515bf6" UNIQUE ("bookingId"), CONSTRAINT "REL_c357057587a1c2afae453515bf" UNIQUE ("bookingId"), CONSTRAINT "CHK_2ea381a5c2f8bef0073a48f6bd" CHECK ("rating" BETWEEN 1 AND 5), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_951b2b14116eb456702bedc9da" ON "reviews" ("guideId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('TOURIST', 'GUIDE', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" citext, "phone" character varying(20), "passwordHash" character varying, "fullName" character varying(120) NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'TOURIST', "phoneVerifiedAt" TIMESTAMP WITH TIME ZONE, "locale" character varying(8) NOT NULL DEFAULT 'en', "avatarUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE TABLE "guide_cities" ("guideId" uuid NOT NULL, "cityId" uuid NOT NULL, CONSTRAINT "PK_4bcd8708be1b2af62c8aac3160a" PRIMARY KEY ("guideId", "cityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82e6e8e234dcf5aab814c37eaa" ON "guide_cities" ("guideId") `);
        await queryRunner.query(`CREATE INDEX "IDX_590d7cd5203b714271b56917e0" ON "guide_cities" ("cityId") `);
        await queryRunner.query(`CREATE TABLE "guide_sites" ("guideId" uuid NOT NULL, "siteId" uuid NOT NULL, CONSTRAINT "PK_e80c8d0d32f02f376c7bdf2fc95" PRIMARY KEY ("guideId", "siteId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ed1f49a9fd6e7e3ad985b4a5e" ON "guide_sites" ("guideId") `);
        await queryRunner.query(`CREATE INDEX "IDX_30708ac6be6ef02ca2c539511f" ON "guide_sites" ("siteId") `);
        await queryRunner.query(`CREATE TABLE "tour_package_sites" ("packageId" uuid NOT NULL, "siteId" uuid NOT NULL, CONSTRAINT "PK_e9f87e7143a8311ab5faec0ce5c" PRIMARY KEY ("packageId", "siteId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d3f30ec74349acae1d982d05f1" ON "tour_package_sites" ("packageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e63a3b157974410ebb39e563c1" ON "tour_package_sites" ("siteId") `);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_78a18a5704f657786240cbe82eb" FOREIGN KEY ("touristId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_7454eb78c9b9345e21a33ad5e34" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_c33a993088cbe955492d812b1b2" FOREIGN KEY ("packageId") REFERENCES "tour_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sos_alerts" ADD CONSTRAINT "FK_1d9158fe8a16cbe60dd55c1494e" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_238a0a4e4dc39f4a8984e633fe3" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cities" ADD CONSTRAINT "FK_b5f9bef6e3609b50aac3e103ab3" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sites" ADD CONSTRAINT "FK_88dfdc5901a77132c246ab6beb5" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guides" ADD CONSTRAINT "FK_6fb9ae622c0f4c05653408ee58f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guides" ADD CONSTRAINT "FK_6c3fcb8d18989d0ba2ee50b373e" FOREIGN KEY ("licenseCountryId") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guide_verification_events" ADD CONSTRAINT "FK_29d9e1bad54935fbebd383a0a91" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tour_packages" ADD CONSTRAINT "FK_2ff20f817e9f4498b3d3ecb746c" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tour_packages" ADD CONSTRAINT "FK_41f97d6bf3b4d424c83d4bb8fda" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c357057587a1c2afae453515bf6" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_951b2b14116eb456702bedc9dac" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_48770372f891b9998360e4434f3" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guide_cities" ADD CONSTRAINT "FK_82e6e8e234dcf5aab814c37eaa9" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "guide_cities" ADD CONSTRAINT "FK_590d7cd5203b714271b56917e0c" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "guide_sites" ADD CONSTRAINT "FK_9ed1f49a9fd6e7e3ad985b4a5ed" FOREIGN KEY ("guideId") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "guide_sites" ADD CONSTRAINT "FK_30708ac6be6ef02ca2c539511f4" FOREIGN KEY ("siteId") REFERENCES "sites"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tour_package_sites" ADD CONSTRAINT "FK_d3f30ec74349acae1d982d05f1b" FOREIGN KEY ("packageId") REFERENCES "tour_packages"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tour_package_sites" ADD CONSTRAINT "FK_e63a3b157974410ebb39e563c1d" FOREIGN KEY ("siteId") REFERENCES "sites"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tour_package_sites" DROP CONSTRAINT "FK_e63a3b157974410ebb39e563c1d"`);
        await queryRunner.query(`ALTER TABLE "tour_package_sites" DROP CONSTRAINT "FK_d3f30ec74349acae1d982d05f1b"`);
        await queryRunner.query(`ALTER TABLE "guide_sites" DROP CONSTRAINT "FK_30708ac6be6ef02ca2c539511f4"`);
        await queryRunner.query(`ALTER TABLE "guide_sites" DROP CONSTRAINT "FK_9ed1f49a9fd6e7e3ad985b4a5ed"`);
        await queryRunner.query(`ALTER TABLE "guide_cities" DROP CONSTRAINT "FK_590d7cd5203b714271b56917e0c"`);
        await queryRunner.query(`ALTER TABLE "guide_cities" DROP CONSTRAINT "FK_82e6e8e234dcf5aab814c37eaa9"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_48770372f891b9998360e4434f3"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_951b2b14116eb456702bedc9dac"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c357057587a1c2afae453515bf6"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d"`);
        await queryRunner.query(`ALTER TABLE "tour_packages" DROP CONSTRAINT "FK_41f97d6bf3b4d424c83d4bb8fda"`);
        await queryRunner.query(`ALTER TABLE "tour_packages" DROP CONSTRAINT "FK_2ff20f817e9f4498b3d3ecb746c"`);
        await queryRunner.query(`ALTER TABLE "guide_verification_events" DROP CONSTRAINT "FK_29d9e1bad54935fbebd383a0a91"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP CONSTRAINT "FK_6c3fcb8d18989d0ba2ee50b373e"`);
        await queryRunner.query(`ALTER TABLE "guides" DROP CONSTRAINT "FK_6fb9ae622c0f4c05653408ee58f"`);
        await queryRunner.query(`ALTER TABLE "sites" DROP CONSTRAINT "FK_88dfdc5901a77132c246ab6beb5"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP CONSTRAINT "FK_b5f9bef6e3609b50aac3e103ab3"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_238a0a4e4dc39f4a8984e633fe3"`);
        await queryRunner.query(`ALTER TABLE "sos_alerts" DROP CONSTRAINT "FK_1d9158fe8a16cbe60dd55c1494e"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_c33a993088cbe955492d812b1b2"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_7454eb78c9b9345e21a33ad5e34"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_78a18a5704f657786240cbe82eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e63a3b157974410ebb39e563c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3f30ec74349acae1d982d05f1"`);
        await queryRunner.query(`DROP TABLE "tour_package_sites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30708ac6be6ef02ca2c539511f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ed1f49a9fd6e7e3ad985b4a5e"`);
        await queryRunner.query(`DROP TABLE "guide_sites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_590d7cd5203b714271b56917e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82e6e8e234dcf5aab814c37eaa"`);
        await queryRunner.query(`DROP TABLE "guide_cities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_951b2b14116eb456702bedc9da"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_escrowstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41f97d6bf3b4d424c83d4bb8fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ff20f817e9f4498b3d3ecb746"`);
        await queryRunner.query(`DROP TABLE "tour_packages"`);
        await queryRunner.query(`DROP TYPE "public"."tour_packages_pricingtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29d9e1bad54935fbebd383a0a9"`);
        await queryRunner.query(`DROP TABLE "guide_verification_events"`);
        await queryRunner.query(`DROP TYPE "public"."guide_verification_events_tostatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."guide_verification_events_fromstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78843aacbd41d7f5d6dbc5522f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3e810892714fd8723b017073c"`);
        await queryRunner.query(`DROP TABLE "guides"`);
        await queryRunner.query(`DROP TYPE "public"."guides_kycstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."guides_verificationstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1516efb8cd9a59205e85a1a9a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a7dbd4513de54a315d97e1a7d"`);
        await queryRunner.query(`DROP TABLE "sites"`);
        await queryRunner.query(`DROP TYPE "public"."sites_category_enum"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89ecbef65dda32fcf45ae09e2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0c5868a3c4663b0e72a6030a6"`);
        await queryRunner.query(`DROP TABLE "cities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ea46f4f2225f38d127063c367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_238a0a4e4dc39f4a8984e633fe"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_resolution_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d9158fe8a16cbe60dd55c1494"`);
        await queryRunner.query(`DROP TABLE "sos_alerts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17c8a50ad52487f8bb826752df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b267d894e32a25ebde4b207a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a18a5704f657786240cbe82e"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ca53c9789e16452c4c202ebfb"`);
        await queryRunner.query(`DROP TABLE "otp_codes"`);
        await queryRunner.query(`DROP TYPE "public"."otp_codes_purpose_enum"`);
    }

}
